# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: liuchong/rustup

    steps:
      - run:
          name: Install Youtube-DL
          command: |
            apt-get update
#            apt-get install youtube-dl -y

#       - run:
#           name: Install Clippy
#           command: |
#             rustup update
#             rustup component add clippy
      
#       - run:
#           name: Check formatting
#           command: |
#             ls
#             cargo clippy --version
#             cargo clippy --verbose
        
      - run:
          name: Stable Build
          command: |
            cargo build --verbose
            
    

