# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: debian-latest

    steps:
#       - run:
#           name: Install Youtube-DL
#           command: |
#             apt-get update
#             apt-get install youtube-dl -y
            
      - run:
          name: Installing Rust
          command: |
            apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh
      
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
        
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
            
    

